### ISSUE TITLE
Valid environment variable names can start with underscore

### ISSUE THREAD

**Issue by jtatarik** [SectorLabs/terraform-provider-circleci#3]
The environment variable name validation is subtly wrong:

https://github.com/SectorLabs/terraform-provider-circleci/blob/fc6d0c923d30fc9298305abce7d7814af6ade9a2/circleci/validation.go#L11

According to POSIX, env var names cannot start with a number, but an underscore is fine. The CircleCI UI, despite CircleCI documentation to the contrary, accepts env variable names starting with underscore. The terraform provider, however, prevents me from creating such variables.

I'd like to have the validation regex modified to allow underscore as a starting character.

**Comment by valentindeaconu** [comment]
Hello! This might be a corner case you're hitting, but according to the documentation, the environment variable **must** start with a letter, as you also mentioned. However, you are right, and in the POSIX documentation, the wording is a bit different. By definition it allows variables to start underscores. Still, since the CircleCI documentation explicitly says that it must start with a letter, I cannot agree to modify the provider and allow it to be done differently. Allowing variables to start with an underscore in the UI is a bug (probably?) and since it is not documented, it can be changed anytime without prior notification.

> [[1](https://circleci.com/docs/env-vars/#environment-variable-usage-options)] CircleCI uses Bash, which follows the POSIX naming convention for environment variables. Valid characters include letters (uppercase and lowercase), digits, and the underscore. **The first character of each environment variable must be a letter.**

> [[2](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html)] Environment variable names [...] consist solely of uppercase letters, digits, and the <underscore> ( '_' ) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap06.html#tagtcjh_3) **and do not begin with a digit**.

**Comment by jtatarik** [comment]
CircleCI have updated their [documentation](https://circleci.com/docs/contexts/#contexts-and-environment-variable-constraints) to match the actual behavior, so I'd like to reopen this issue:


> The environment variable name must be:
>
>    300 or fewer characters
>
>    Begin with an alpha (a-z, A-Z) or _ as the first character, and use alphanumeric or _ for the remaining characters
